termites:
    builder:
        count: 250
        movement_spaces: 5
        wander_weight: 1
        place_probability: 0.1
        min_place_pheromone: 0.1
        max_place_pheromone: 0.5
        pheromone_lay_rate: 1
        default_block: GOLD_BLOCK
        death_on_build: true
    queen:
        pheromone_lay_rate: 1000
    trail:
        wander_weight: 1
        pheromone_lay_rate: 6.5
pheromone:
    diffuse_rate: 0.145
    evaporation_rate: 0.9
    diffuse_rate_trail: 0.166
    evaporation_rate_trail: 0.95
boundary:
    y_up_max: 20
    y_down_max: 10
timesteps:
    builder_start: 500
    finish: 2250