/*
 * MCNestBuilderGUIView.java
 */

package mcnestbuildergui;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.Task;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import mcloader.MinecraftWorld;

/**
 * The application's main frame.
 */
public class MCNestBuilderGUIView extends FrameView {

    public MCNestBuilderGUIView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jButtonSelectPath = new javax.swing.JButton();
        jTextFieldMinecraftPath = new javax.swing.JTextField();
        jRadioButtonWorld1 = new javax.swing.JRadioButton();
        jRadioButtonWorld2 = new javax.swing.JRadioButton();
        jRadioButtonWorld3 = new javax.swing.JRadioButton();
        jRadioButtonWorld4 = new javax.swing.JRadioButton();
        jRadioButtonWorld5 = new javax.swing.JRadioButton();
        jButtonRun = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        buttonGroupWorlds = new javax.swing.ButtonGroup();
        minecraftPathChooser = new javax.swing.JFileChooser();

        mainPanel.setName("mainPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(mcnestbuildergui.MCNestBuilderGUIApp.class).getContext().getActionMap(MCNestBuilderGUIView.class, this);
        jButtonSelectPath.setAction(actionMap.get("selectMinecraftPath")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mcnestbuildergui.MCNestBuilderGUIApp.class).getContext().getResourceMap(MCNestBuilderGUIView.class);
        jButtonSelectPath.setText(resourceMap.getString("jButtonSelectPath.text")); // NOI18N
        jButtonSelectPath.setActionCommand(resourceMap.getString("jButtonSelectPath.actionCommand")); // NOI18N
        jButtonSelectPath.setName("jButtonSelectPath"); // NOI18N

        jTextFieldMinecraftPath.setText(resourceMap.getString("jTextFieldMinecraftPath.text")); // NOI18N
        jTextFieldMinecraftPath.setName("jTextFieldMinecraftPath"); // NOI18N

        buttonGroupWorlds.add(jRadioButtonWorld1);
        jRadioButtonWorld1.setText(resourceMap.getString("jRadioButtonWorld1.text")); // NOI18N
        jRadioButtonWorld1.setName("jRadioButtonWorld1"); // NOI18N

        buttonGroupWorlds.add(jRadioButtonWorld2);
        jRadioButtonWorld2.setText(resourceMap.getString("jRadioButtonWorld2.text")); // NOI18N
        jRadioButtonWorld2.setName("jRadioButtonWorld2"); // NOI18N

        buttonGroupWorlds.add(jRadioButtonWorld3);
        jRadioButtonWorld3.setText(resourceMap.getString("jRadioButtonWorld3.text")); // NOI18N
        jRadioButtonWorld3.setName("jRadioButtonWorld3"); // NOI18N

        buttonGroupWorlds.add(jRadioButtonWorld4);
        jRadioButtonWorld4.setText(resourceMap.getString("jRadioButtonWorld4.text")); // NOI18N
        jRadioButtonWorld4.setName("jRadioButtonWorld4"); // NOI18N

        buttonGroupWorlds.add(jRadioButtonWorld5);
        jRadioButtonWorld5.setText(resourceMap.getString("jRadioButtonWorld5.text")); // NOI18N
        jRadioButtonWorld5.setName("jRadioButtonWorld5"); // NOI18N

        jButtonRun.setAction(actionMap.get("runProgram")); // NOI18N
        jButtonRun.setText(resourceMap.getString("buttonRun.text")); // NOI18N
        jButtonRun.setName("buttonRun"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonWorld5)
                    .addComponent(jRadioButtonWorld4)
                    .addComponent(jRadioButtonWorld3)
                    .addComponent(jRadioButtonWorld2)
                    .addComponent(jRadioButtonWorld1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jButtonSelectPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMinecraftPath, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                    .addComponent(jButtonRun, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMinecraftPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectPath, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonWorld1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonWorld2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonWorld3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonWorld4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonWorld5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButtonRun)
                .addContainerGap())
        );

        jButtonRun.getAccessibleContext().setAccessibleName(resourceMap.getString("jButton2.AccessibleContext.accessibleName")); // NOI18N

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        minecraftPathChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        minecraftPathChooser.setName("minecraftPathChooser"); // NOI18N

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void selectMinecraftPath() {
        if (minecraftPathChooser.showOpenDialog(mainPanel) == minecraftPathChooser.APPROVE_OPTION)
            jTextFieldMinecraftPath.setText(minecraftPathChooser.getSelectedFile().getPath());
    }

    @Action
    public Task runProgram() {
        return new RunProgramTask(getApplication());
    }

    private class RunProgramTask extends org.jdesktop.application.Task<Object, Void> {
        RunProgramTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to RunProgramTask fields, here.
            super(app);

            // start the progress bar
            progressBar.setVisible(true);
            progressBar.setValue(0);

            // find the name of the desired world
            String worldName = "";
            if (jRadioButtonWorld1.isSelected()) {
            worldName = "World1";
            } else if (jRadioButtonWorld2.isSelected()) {
            worldName = "World2";
            } else if (jRadioButtonWorld3.isSelected()) {
            worldName = "World3";
            } else if (jRadioButtonWorld4.isSelected()) {
            worldName = "World4";
            } else if (jRadioButtonWorld5.isSelected()) {
            worldName = "World5";
            }

            // find the .minecraft save game path
            String minecraftPath = jTextFieldMinecraftPath.getText();

            // load the world at the combined path
            MinecraftWorld minecraftWorld = new MinecraftWorld(minecraftPath + "/saves/", worldName);

            try {
                minecraftWorld.loadData();
                progressBar.setValue(25);
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(mainPanel, new JLabel(e.getMessage()), "Complete", JOptionPane.INFORMATION_MESSAGE);
            }

            // TODO: Insert code to do world alterations...
            byte[][][] blocks = minecraftWorld.getWorldBlocks();

            // tell the user that we are done
            progressBar.setValue(100);
            JOptionPane.showMessageDialog(mainPanel, new JLabel("The Minecraft save in '" + worldName + "' has been modified."), "Complete", JOptionPane.INFORMATION_MESSAGE);
            progressBar.setVisible(false);
        }
        @Override protected Object doInBackground() {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            return null;  // return your result
        }
        @Override protected void succeeded(Object result) {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupWorlds;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JButton jButtonSelectPath;
    private javax.swing.JRadioButton jRadioButtonWorld1;
    private javax.swing.JRadioButton jRadioButtonWorld2;
    private javax.swing.JRadioButton jRadioButtonWorld3;
    private javax.swing.JRadioButton jRadioButtonWorld4;
    private javax.swing.JRadioButton jRadioButtonWorld5;
    private javax.swing.JTextField jTextFieldMinecraftPath;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JFileChooser minecraftPathChooser;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
